### ISSUE TITLE
SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by Dids** [markbao/node-diffbot#6]
SyntaxError: Unexpected token <
    at Object.parse (native)
    at Request._callback (node_modules/diffbot/lib/diffbot.js:77:28)

**Comment by hitubansal123** [comment]
Still getting same issue

**Comment by Dids** [comment]
Try with this version:
```
npm install github:Dids/node-diffbot
```

**Comment by markbao** [comment]
Closed thanks to #7.
